hongs:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    host: localhost
    port: 3306
    database: sky_take_out

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: hongs-cai-java-sky-take-out
    region: cn-beijing

  redis:
    host: localhost
    port: 6379
    password: ~

  jwt:
    admin-secret-key: hongs
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: hongs
    user-ttl: 7200000
    user-token-name: user_token

  wechat:
    app-id: ${WECHAT_APP_ID}
    app-secret: ${WECHAT_APP_SECRET}
